package com.xianglin.appserv.common.dal.dataobject;

import java.util.Date;

public class PermanetCalendar {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permanet_calendar.id
     *
     * @mbggenerated Thu Sep 29 10:55:41 CST 2016
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permanet_calendar.yearMonth
     *
     * @mbggenerated Thu Sep 29 10:55:41 CST 2016
     */
    private String yearmonth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permanet_calendar.dayCount
     *
     * @mbggenerated Thu Sep 29 10:55:41 CST 2016
     */
    private String daycount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permanet_calendar.festivalInfo
     *
     * @mbggenerated Thu Sep 29 10:55:41 CST 2016
     */
    private String festivalinfo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permanet_calendar.lumarInfo1
     *
     * @mbggenerated Thu Sep 29 10:55:41 CST 2016
     */
    private String lumarinfo1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permanet_calendar.lumarInfo2
     *
     * @mbggenerated Thu Sep 29 10:55:41 CST 2016
     */
    private String lumarinfo2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permanet_calendar.dayViewYiDescContent
     *
     * @mbggenerated Thu Sep 29 10:55:41 CST 2016
     */
    private String dayviewyidesccontent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permanet_calendar.dayViewJiDescContent
     *
     * @mbggenerated Thu Sep 29 10:55:41 CST 2016
     */
    private String dayviewjidesccontent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permanet_calendar.pzbj
     *
     * @mbggenerated Thu Sep 29 10:55:41 CST 2016
     */
    private String pzbj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permanet_calendar.jsyq
     *
     * @mbggenerated Thu Sep 29 10:55:41 CST 2016
     */
    private String jsyq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permanet_calendar.xsyj
     *
     * @mbggenerated Thu Sep 29 10:55:41 CST 2016
     */
    private String xsyj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permanet_calendar.cs
     *
     * @mbggenerated Thu Sep 29 10:55:41 CST 2016
     */
    private String cs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permanet_calendar.wx
     *
     * @mbggenerated Thu Sep 29 10:55:41 CST 2016
     */
    private String wx;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permanet_calendar.create_date
     *
     * @mbggenerated Thu Sep 29 10:55:41 CST 2016
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permanet_calendar.comment
     *
     * @mbggenerated Thu Sep 29 10:55:41 CST 2016
     */
    private String comment;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permanet_calendar.id
     *
     * @return the value of permanet_calendar.id
     *
     * @mbggenerated Thu Sep 29 10:55:41 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permanet_calendar.id
     *
     * @param id the value for permanet_calendar.id
     *
     * @mbggenerated Thu Sep 29 10:55:41 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permanet_calendar.yearMonth
     *
     * @return the value of permanet_calendar.yearMonth
     *
     * @mbggenerated Thu Sep 29 10:55:41 CST 2016
     */
    public String getYearmonth() {
        return yearmonth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permanet_calendar.yearMonth
     *
     * @param yearmonth the value for permanet_calendar.yearMonth
     *
     * @mbggenerated Thu Sep 29 10:55:41 CST 2016
     */
    public void setYearmonth(String yearmonth) {
        this.yearmonth = yearmonth == null ? null : yearmonth.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permanet_calendar.dayCount
     *
     * @return the value of permanet_calendar.dayCount
     *
     * @mbggenerated Thu Sep 29 10:55:41 CST 2016
     */
    public String getDaycount() {
        return daycount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permanet_calendar.dayCount
     *
     * @param daycount the value for permanet_calendar.dayCount
     *
     * @mbggenerated Thu Sep 29 10:55:41 CST 2016
     */
    public void setDaycount(String daycount) {
        this.daycount = daycount == null ? null : daycount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permanet_calendar.festivalInfo
     *
     * @return the value of permanet_calendar.festivalInfo
     *
     * @mbggenerated Thu Sep 29 10:55:41 CST 2016
     */
    public String getFestivalinfo() {
        return festivalinfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permanet_calendar.festivalInfo
     *
     * @param festivalinfo the value for permanet_calendar.festivalInfo
     *
     * @mbggenerated Thu Sep 29 10:55:41 CST 2016
     */
    public void setFestivalinfo(String festivalinfo) {
        this.festivalinfo = festivalinfo == null ? null : festivalinfo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permanet_calendar.lumarInfo1
     *
     * @return the value of permanet_calendar.lumarInfo1
     *
     * @mbggenerated Thu Sep 29 10:55:41 CST 2016
     */
    public String getLumarinfo1() {
        return lumarinfo1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permanet_calendar.lumarInfo1
     *
     * @param lumarinfo1 the value for permanet_calendar.lumarInfo1
     *
     * @mbggenerated Thu Sep 29 10:55:41 CST 2016
     */
    public void setLumarinfo1(String lumarinfo1) {
        this.lumarinfo1 = lumarinfo1 == null ? null : lumarinfo1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permanet_calendar.lumarInfo2
     *
     * @return the value of permanet_calendar.lumarInfo2
     *
     * @mbggenerated Thu Sep 29 10:55:41 CST 2016
     */
    public String getLumarinfo2() {
        return lumarinfo2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permanet_calendar.lumarInfo2
     *
     * @param lumarinfo2 the value for permanet_calendar.lumarInfo2
     *
     * @mbggenerated Thu Sep 29 10:55:41 CST 2016
     */
    public void setLumarinfo2(String lumarinfo2) {
        this.lumarinfo2 = lumarinfo2 == null ? null : lumarinfo2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permanet_calendar.dayViewYiDescContent
     *
     * @return the value of permanet_calendar.dayViewYiDescContent
     *
     * @mbggenerated Thu Sep 29 10:55:41 CST 2016
     */
    public String getDayviewyidesccontent() {
        return dayviewyidesccontent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permanet_calendar.dayViewYiDescContent
     *
     * @param dayviewyidesccontent the value for permanet_calendar.dayViewYiDescContent
     *
     * @mbggenerated Thu Sep 29 10:55:41 CST 2016
     */
    public void setDayviewyidesccontent(String dayviewyidesccontent) {
        this.dayviewyidesccontent = dayviewyidesccontent == null ? null : dayviewyidesccontent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permanet_calendar.dayViewJiDescContent
     *
     * @return the value of permanet_calendar.dayViewJiDescContent
     *
     * @mbggenerated Thu Sep 29 10:55:41 CST 2016
     */
    public String getDayviewjidesccontent() {
        return dayviewjidesccontent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permanet_calendar.dayViewJiDescContent
     *
     * @param dayviewjidesccontent the value for permanet_calendar.dayViewJiDescContent
     *
     * @mbggenerated Thu Sep 29 10:55:41 CST 2016
     */
    public void setDayviewjidesccontent(String dayviewjidesccontent) {
        this.dayviewjidesccontent = dayviewjidesccontent == null ? null : dayviewjidesccontent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permanet_calendar.pzbj
     *
     * @return the value of permanet_calendar.pzbj
     *
     * @mbggenerated Thu Sep 29 10:55:41 CST 2016
     */
    public String getPzbj() {
        return pzbj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permanet_calendar.pzbj
     *
     * @param pzbj the value for permanet_calendar.pzbj
     *
     * @mbggenerated Thu Sep 29 10:55:41 CST 2016
     */
    public void setPzbj(String pzbj) {
        this.pzbj = pzbj == null ? null : pzbj.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permanet_calendar.jsyq
     *
     * @return the value of permanet_calendar.jsyq
     *
     * @mbggenerated Thu Sep 29 10:55:41 CST 2016
     */
    public String getJsyq() {
        return jsyq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permanet_calendar.jsyq
     *
     * @param jsyq the value for permanet_calendar.jsyq
     *
     * @mbggenerated Thu Sep 29 10:55:41 CST 2016
     */
    public void setJsyq(String jsyq) {
        this.jsyq = jsyq == null ? null : jsyq.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permanet_calendar.xsyj
     *
     * @return the value of permanet_calendar.xsyj
     *
     * @mbggenerated Thu Sep 29 10:55:41 CST 2016
     */
    public String getXsyj() {
        return xsyj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permanet_calendar.xsyj
     *
     * @param xsyj the value for permanet_calendar.xsyj
     *
     * @mbggenerated Thu Sep 29 10:55:41 CST 2016
     */
    public void setXsyj(String xsyj) {
        this.xsyj = xsyj == null ? null : xsyj.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permanet_calendar.cs
     *
     * @return the value of permanet_calendar.cs
     *
     * @mbggenerated Thu Sep 29 10:55:41 CST 2016
     */
    public String getCs() {
        return cs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permanet_calendar.cs
     *
     * @param cs the value for permanet_calendar.cs
     *
     * @mbggenerated Thu Sep 29 10:55:41 CST 2016
     */
    public void setCs(String cs) {
        this.cs = cs == null ? null : cs.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permanet_calendar.wx
     *
     * @return the value of permanet_calendar.wx
     *
     * @mbggenerated Thu Sep 29 10:55:41 CST 2016
     */
    public String getWx() {
        return wx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permanet_calendar.wx
     *
     * @param wx the value for permanet_calendar.wx
     *
     * @mbggenerated Thu Sep 29 10:55:41 CST 2016
     */
    public void setWx(String wx) {
        this.wx = wx == null ? null : wx.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permanet_calendar.create_date
     *
     * @return the value of permanet_calendar.create_date
     *
     * @mbggenerated Thu Sep 29 10:55:41 CST 2016
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permanet_calendar.create_date
     *
     * @param createDate the value for permanet_calendar.create_date
     *
     * @mbggenerated Thu Sep 29 10:55:41 CST 2016
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permanet_calendar.comment
     *
     * @return the value of permanet_calendar.comment
     *
     * @mbggenerated Thu Sep 29 10:55:41 CST 2016
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permanet_calendar.comment
     *
     * @param comment the value for permanet_calendar.comment
     *
     * @mbggenerated Thu Sep 29 10:55:41 CST 2016
     */
    public void setComment(String comment) {
        this.comment = comment == null ? null : comment.trim();
    }

	@Override
	public String toString() {
		return "PermanetCaldendar [id=" + id + ", yearmonth=" + yearmonth + ", daycount=" + daycount + ", festivalinfo="
				+ festivalinfo + ", lumarinfo1=" + lumarinfo1 + ", lumarinfo2=" + lumarinfo2 + ", dayviewyidesccontent="
				+ dayviewyidesccontent + ", dayviewjidesccontent=" + dayviewjidesccontent + ", pzbj=" + pzbj + ", jsyq="
				+ jsyq + ", xsyj=" + xsyj + ", cs=" + cs + ", wx=" + wx + ", createDate=" + createDate + ", comment="
				+ comment + "]";
	}
    
}